let mapleader = "''"

syntax on
set number
set noswapfile
set hlsearch
set ignorecase
set incsearch

set backspace=indent,eol,start

" required for rust plugin
filetype plugin indent on

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
