# Load starship
eval "$(starship init zsh)"

# Load shell aliases
source ~/.config/zsh/alias.zsh

# Load zsh options
source ~/.config/zsh/setopt.zsh

# Load keybindings
source ~/.config/zsh/keybinds.zsh

# Pyenv
eval export PATH="/Users/qtc1112/.pyenv/shims:${PATH}"
export PYENV_SHELL=zsh
source '/usr/local/Cellar/pyenv/1.2.23/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  activate|deactivate|rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}
