# Load starship
eval "$(starship init zsh)"

# Load shell aliases
source ~/.config/zsh/alias.zsh

# Load zsh options
source ~/.config/zsh/setopt.zsh

# Load keybindings
source ~/.config/zsh/keybinds.zsh
